import Padrao from './Padrao';
import HomeScreen from './Home/HomeScreen';
import JogoScreen from './Jogo/JogoScreen';
import ResultadoScreen from './Resultados/ResultadosScreen';
import ClassificacaoScreen from './Classificacao/ClassificacaoScreen';
import HistoricoScreen from './Historico/HistoricoScreen';
import CompraCifrasScreen from './CompraCifras/CompraCifras';
import PerfilScreen from './Perfil/VerPerfil';
import IndicacoesScreen from './Indicacoes/IndicacoesScreen';
export default {Padrao, HomeScreen, JogoScreen, ResultadoScreen, ClassificacaoScreen, HistoricoScreen, CompraCifrasScreen, PerfilScreen, IndicacoesScreen};